channels:
- conda-forge
dependencies:
- python=3.11.1
- pip<=24.3.1
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.0
  - imbalanced-learn==0.13.0
  - numpy==2.2.1
  - pandas==2.2.3
  - psutil==6.1.1
  - scikit-learn==1.6.1
  - scipy==1.15.1
name: mlflow-env
